language: go

go:
  - 1.5
  - 1.6
  - tip

sudo: required
services:
  - docker

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y gcc libkrb5-dev

install: true

script:
  - go vet ./...
  - go fmt ./...
  - go test -v -race ./...
  - cd test/
  - ./run-heimdal.sh
